name: kirin_web
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'
flutter:
  uses-material-design: true
#  assets:
#    - web/assets/images/logo-GDG.svg
#    - web/assets/images/logo-GDG.png
  fonts:
    - family: Google
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
dependencies:
  flutter_web: any
  flutter_web_ui: any
#  flutter_svg: ^0.12.4+2
#  firebase_core: ^0.4.0+3
#  firebase_analytics: ^3.0.2
#  firebase_crashlytics: ^0.0.4+4
#  firebase_storage: ^3.0.1

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
